import { hasLocale } from 'next-intl';
import { getRequestConfig } from 'next-intl/server';
import { locale as localeParam } from 'next/root-params';
import { routing } from './routing';

/**
 * Resolves the messages for the request's locale.
 *
 * Reads the locale from `next/root-params` rather than from
 * `getRequestConfig`'s `requestLocale`, which next-intl deprecated in favour
 * of it. The practical difference is rendering mode: `requestLocale` resolves
 * through `headers()`, which opts every page into dynamic rendering, whereas a
 * root param is known per prerendered path and lets the pages stay static.
 * For a portfolio that is almost entirely static content, that is the
 * difference between serving cached HTML and rendering on every visit.
 *
 * The export name comes from the folder: `app/[locale]` gives `locale`. Its
 * types are generated by `next typegen`.
 *
 * An unknown locale falls back to the default rather than throwing, since the
 * segment acts as a catch-all -- a request for `/unknown.txt` reaches here too.
 */
export default getRequestConfig(async () => {
  const requested = await localeParam();
  const locale = hasLocale(routing.locales, requested)
    ? requested
    : routing.defaultLocale;

  return {
    locale,
    messages: (await import(`../messages/${locale}.json`)).default,
  };
});
